### ISSUE TITLE
Issue with selected value.

### ISSUE THREAD

**Issue by surajde16** [maheshwarishivam/ionic-select-search#1]
Hello,
Plugin is working fine when the selected-value attribute  is "selectedValue". Am able to get  proper selected id of the option value.
But when i change attribute name to "some_id". On change first change id returned is blank. Again on next change it returns the previous selected id.

Please advise if there any work around for this issue.

Thank you.

**Comment by surajde16** [comment]
Hello,
Sorry, issue was with my attribute select-changed="doSomethingWithSelectedValue(some_id)".
I should had used selectedValue instead of some_id.
That solved my problem.
Thanks for great plugin.

**Comment by maheshwarishivam** [comment]
Sorry for the delay in response.
Glad that the issue is solved :)
